WaiterService/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WaiterService.Models
{
    public class Location
    {
        public int ID { get; set; }
         
        [Display(Name = "Location Name")]
        public string Name { get; set; }

        [Display(Name = "Zip Code")]
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }

        public string ProfileId { get; set; }
        public Profile Profile { get; set; }
    }
}

WaiterService/Models/ViewModels/LocationViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WaiterService.Models.ViewModels
{
    public class LocationViewModel : Location
    {
        public string Lat
        {
            get { return Latitude.ToString(); }
            set { Latitude = float.Parse(value); }
        }

        public string Long
        {
            get { return Longitude.ToString(); }
            set { Longitude = float.Parse(value); }
        }
    }
}

WaiterService/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using WaiterService.Models;
using WaiterService.Models.AccountViewModels;
using WaiterService.Services;
using WaiterService.Middleware;
using WaiterService.Data;
using WaiterService.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace WaiterService.Controllers
{
    [Authorize(Roles = "Company")]
    public class LocationController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly ApplicationDbContext _context;

        public LocationController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ApplicationDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        
        //GET: /Location/View
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = User.Identity.GetUserId();

            var query = from locations in _context.Set<Location>()
                        where locations.ProfileId == userId
                        select locations;

            var model = await query.ToArrayAsync();

            return View(model);
        }

        //GET: /Location/Create
        [HttpGet]
        public IActionResult Create()
        {
            var model = new LocationViewModel();
            return View(model);
        }

        //POST: /Location/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LocationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                // If we got this far, something failed, redisplay form
                return View(model);
            }

            model.ProfileId = User.Identity.GetUserId();

            _context.Locations.Add(new Location().Assign(model));
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        //GET: /Location/Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var userId = User.Identity.GetUserId();

            var query = from location in _context.Set<Location>()
                        where location.ProfileId == userId
                        where location.ID == id
                        select location;

            var model = await query.FirstOrDefaultAsync();

            if (model == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(new LocationViewModel().Assign(model));
        }


        //POST: /Location/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(LocationViewModel model)
        {
            var userId = User.Identity.GetUserId();

            if (!ModelState.IsValid)
            {
                // If we got this far, something failed, redisplay form
                return View(model);
            }

            var location = _context.Locations
                            .Where(l => l.ProfileId == userId)
                            .FirstOrDefault(e => e.ID == model.ID);

            location.Assign(model);
            _context.Locations.Update(location);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

WaiterService/Views/Location/Index.cshtml
@model Location[]
@{
    ViewData["Title"] = "Locations";
    var count = 0;
}

@section Styles
{
    <link href="~/lib/selectize/dist/css/selectize.css" rel="stylesheet" />
}


<div class="container">
    <div class="col-md-offset-2 col-md-8">
        <h4>Your Locations</h4>
        <hr />

        <a asp-controller="Location" asp-action="Create" class="btn btn-default mr-xs mb-sm">Add New Location</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        ZipCode
                    </th>
                    <th>
                        State
                    </th>
                    <th>
                        Country
                    </th>
                    <th>
                        
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var Location in Model)
                    {
                        <tr>
                            <td>
                                @(++count)
                            </td>
                            <td>
                                @Location.Name
                            </td>
                            <td>
                                @Location.ZipCode
                            </td>
                            <td>
                                @Location.State
                            </td>
                            <td>
                                @Location.Country
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="Location" asp-route-id="@Location.ID" class="btn btn-default btn-xs mr-xs mb-sm">Edit</a>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/lib/selectize/dist/js/standalone/selectize.min.js"></script>

    <script>
        $(document).ready(function () {
            
        });
    </script>
}