WaiterService/Models/Experience.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaiterService.Models
{
    public abstract class Experience
    {
        public int ID { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public int SkillId { get; set; }
        public Skill Skill { get; set; }
    }

    public class ExperienceMatch : Experience
    {

    }

    public static class ExperienceExtentions
    {
        public static List<ExperienceMatch> ToExperienceMatch<T> (this List<T> src)
        {
            return src.Select(e => new ExperienceMatch().Assign(e)).ToList();
        }
    }

    public class ExperienceComparer : IEqualityComparer<Experience>
    {
        public bool Equals(Experience x, Experience y)
        {
            return (x.SkillId == y.SkillId && x.CategoryId == y.CategoryId);
        }

        public int GetHashCode(Experience obj)
        {
            return new { obj.SkillId, obj.CategoryId }.GetHashCode();
        }
    }
}

WaiterService/Models/ViewModels/ExperienceViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WaiterService.Models.ViewModels
{
    public class ExperienceViewModel : UserExperience
    {
        public List<SelectListItem> CategoriesList { get; set; }
        public List<SelectListItem> SkillsList { get; set; }
    }
}

WaiterService/Controllers/ExperienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using WaiterService.Models;
using WaiterService.Models.AccountViewModels;
using WaiterService.Services;
using WaiterService.Middleware;
using WaiterService.Data;
using WaiterService.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace WaiterService.Controllers
{
    [Authorize(Roles = "User")]
    public class ExperienceController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly ApplicationDbContext _context;

        public ExperienceController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ApplicationDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        
        //GET: /Experience/View
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = User.Identity.GetUserId();

            var query = from experiences in _context.Set<UserExperience>()
                        .Include(e => e.Category)
                        .Include(e => e.Skill)
                        where experiences.ProfileId == userId
                        select experiences;

            var model = await query.ToArrayAsync();

            return View(model);
        }

        //GET: /Experience/Create
        [HttpGet]
        public IActionResult Create()
        {
            var model = new ExperienceViewModel();

            var categories = _context.Categories.ToList();
            var skills = _context.Skills.ToList();
            model.CategoriesList = categories.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = Convert.ToString(c.ID)
            }).ToList();
            model.SkillsList = skills.Select(s => new SelectListItem()
            {
                Text = s.Name,
                Value = Convert.ToString(s.ID)
            }).ToList();

            return View(model);
        }

        //POST: /Experience/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExperienceViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.ProfileId = User.Identity.GetUserId();
                var experience = new UserExperience().Assign(model);
                
                _context.UserExperiences.Add(experience);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            var categories = _context.Categories.ToList();
            var skills = _context.Skills.ToList();

            model.CategoriesList = categories.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = Convert.ToString(c.ID)
            }).ToList();
            model.SkillsList = skills.Select(s => new SelectListItem()
            {
                Text = s.Name,
                Value = Convert.ToString(s.ID)
            }).ToList();

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //GET: /Experience/Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var userId = User.Identity.GetUserId();

            var query = from experience in _context.Set<UserExperience>()
                        .Include(e => e.Category)
                        .Include(e => e.Skill)
                        where experience.ProfileId == userId
                        where experience.ID == id
                        select experience;

            var record = await query.FirstOrDefaultAsync();

            if (record == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var model = new ExperienceViewModel().Assign(record);

            var categories = _context.Categories.ToList();
            var skills = _context.Skills.ToList();
            model.CategoriesList = categories.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = Convert.ToString(c.ID)
            }).ToList();
            model.SkillsList = skills.Select(s => new SelectListItem()
            {
                Text = s.Name,
                Value = Convert.ToString(s.ID)
            }).ToList();

            return View(model);
        }


        //POST: /Experience/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ExperienceViewModel model)
        {
            var userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                var experience = _context.UserExperiences
                                .Where(e => e.ProfileId == userId)
                                .FirstOrDefault(e => e.ID == model.ID);

                experience.Assign(model);
                _context.UserExperiences.Update(experience);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            var categories = _context.Categories.ToList();
            var skills = _context.Skills.ToList();

            model.CategoriesList = categories.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = Convert.ToString(c.ID)
            }).ToList();
            model.SkillsList = skills.Select(s => new SelectListItem()
            {
                Text = s.Name,
                Value = Convert.ToString(s.ID)
            }).ToList();

            // If we got this far, something failed, redisplay form
            return View(model);
        }
    }
}

WaiterService/Views/Experience/Create.cshtml
@model ExperienceViewModel
@{
    ViewData["Title"] = "New Skill";
}

@section Styles
{
    <link href="~/lib/selectize/dist/css/selectize.css" rel="stylesheet" />
    <link href="~/lib/selectize/dist/css/selectize.default.css" rel="stylesheet" />
    <link href="~/lib/selectize/dist/css/selectize.bootstrap3.css" rel="stylesheet" />
}


<div class="container">
    <div class="col-md-6">
        <form asp-controller="Experience" asp-action="Create" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
            <input asp-for="ProfileId" hidden />
            <h4>Add new Skill.</h4>
            <hr />

            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="row">
                <div class="col-md-12">
                    <h4 class="mt-xl mb-lg pb-none text-uppercase">Skill Details</h4>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6">
                    <label for="CategoryId" class="control-label">Category: </label>
                    <select asp-for="CategoryId" asp-items="Model.CategoriesList" class="form-control"></select>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label for="SkillId" class="control-label">Skill: </label>
                    <select asp-for="SkillId" asp-items="Model.SkillsList" class="form-control"></select>
                    <span asp-validation-for="SkillId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <label asp-for="Months" class="control-label" placeholder="Type in an address" autocomplete="off"></label>
                    <input asp-for="Months" class="form-control" />
                    <span asp-validation-for="Months" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-6 col-md-6">
                    <label class="control-label">&nbsp;</label>
                    <br />
                    <button type="submit" class="btn btn-default pull-right">Add Skill</button>
                </div>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    
    <script src="~/lib/selectize/dist/js/standalone/selectize.min.js"></script>

    <script>
        $(document).ready(function () {
            $(function () {
                // Selectize
                $("#CategoryId").selectize();
                $("#SkillId").selectize();

            });
        });
    </script>
}

WaiterService/Views/Experience/Edit.cshtml
@model ExperienceViewModel
@{
    ViewData["Title"] = "Edit Experience";
}

@section Styles
{
    <link href="~/lib/selectize/dist/css/selectize.css" rel="stylesheet" />
}


<div class="container">
    <div class="col-md-6">
        <form asp-controller="Experience" asp-action="Edit" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
            <input asp-for="ProfileId" hidden />
            <input asp-for="ID" hidden />
            <h4>Edit Skill.</h4>
            <hr />

            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="row">
                <div class="col-md-12">
                    <h4 class="mt-xl mb-lg pb-none text-uppercase">Skill Details</h4>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6">
                    <label for="CategoryId" class="control-label">Category: </label>
                    <select asp-for="CategoryId" asp-items="Model.CategoriesList" class="form-control"></select>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label for="SkillId" class="control-label">Skill: </label>
                    <select asp-for="SkillId" asp-items="Model.SkillsList" class="form-control"></select>
                    <span asp-validation-for="SkillId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <label asp-for="Months" class="control-label" placeholder="Type in an address" autocomplete="off"></label>
                    <input asp-for="Months" class="form-control" />
                    <span asp-validation-for="Months" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-6 col-md-6">
                    <label class="control-label">&nbsp;</label>
                    <br />
                    <button type="submit" class="btn btn-default pull-right">Update Skill</button>
                </div>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <script src="~/lib/selectize/dist/js/standalone/selectize.min.js"></script>

    <script>
        $(document).ready(function () {
            // Selectize
            $("#Experience_CategoryId").selectize();
            $("#Experience_SkillId").selectize();
        });
    </script>
}

WaiterService/Views/Experience/Index.cshtml
@model UserExperience[]
@{
    ViewData["Title"] = "Skills";
    var count = 0;
}

@section Styles
{
    <link href="~/lib/selectize/dist/css/selectize.css" rel="stylesheet" />
}


<div class="container">
    <div class="col-md-offset-2 col-md-8">
        <h4>Your Experiences</h4>
        <hr />

        <a asp-controller="Experience" asp-action="Create" class="btn btn-default mr-xs mb-sm">Add New Skill</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Skill
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Period (Months)
                    </th>
                    <th>
                        
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var Experience in Model)
                    {
                        <tr>
                            <td>
                                @(++count)
                            </td>
                            <td>
                                @Experience.Skill.Name
                            </td>
                            <td>
                                @Experience.Category.Name
                            </td>
                            <td>
                                @Experience.Months
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="Experience" asp-route-id="@Experience.ID" class="btn btn-default btn-xs mr-xs mb-sm">Edit</a>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/lib/selectize/dist/js/standalone/selectize.min.js"></script>

    <script>
        $(document).ready(function () {
            
        });
    </script>
}