WaiterService/Models/Education.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WaiterService.Models
{
    public class Education
    {
        public int ID { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Institution { get; set; }
        public string Address { get; set; }
        [Display(Name = "Start Year")]
        [Required]
        public int StartYear { get; set; }
        [Display(Name = "End Year")]
        [Required]
        public int EndYear { get; set; }

        public string ProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
    }
}

WaiterService/Controllers/EducationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using WaiterService.Models;
using WaiterService.Models.AccountViewModels;
using WaiterService.Services;
using WaiterService.Middleware;
using WaiterService.Data;
using Microsoft.EntityFrameworkCore;

namespace WaiterService.Controllers
{
    [Authorize]
    public class EducationController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly ApplicationDbContext _context;

        public EducationController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ApplicationDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }


        //GET: /Education/View
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = User.Identity.GetUserId();

            var query = from locations in _context.Set<Education>()
                        where locations.ProfileId == userId
                        select locations;

            var model = await query.ToArrayAsync();

            return View(model);
        }

        //GET: /Education/Create
        [HttpGet]
        public IActionResult Create()
        {
            var model = new Education();
            return View(model);
        }

        //POST: /Education/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Education model)
        {
            if (!ModelState.IsValid)
            {
                // If we got this far, something failed, redisplay form
                return View(model);
            }

            model.ProfileId = User.Identity.GetUserId();

            _context.Educations.Add(new Education().Assign(model));
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        //GET: /Education/Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var userId = User.Identity.GetUserId();

            var query = from location in _context.Set<Education>()
                        where location.ProfileId == userId
                        where location.ID == id
                        select location;

            var model = await query.FirstOrDefaultAsync();

            if (model == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(new Education().Assign(model));
        }


        //POST: /Education/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Education model)
        {
            var userId = User.Identity.GetUserId();

            if (!ModelState.IsValid)
            {
                // If we got this far, something failed, redisplay form
                return View(model);
            }

            var education = _context.Educations
                            .Where(l => l.ProfileId == userId)
                            .FirstOrDefault(e => e.ID == model.ID);

            education.Assign(model);
            _context.Educations.Update(education);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

WaiterService/Views/Education/Create.cshtml
@model Education
@{
    ViewData["Title"] = "New Education";
}

@section Styles
{
    
}

<div class="container">
    <div class="col-md-6">
        <form asp-controller="Education" asp-action="Create" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
            <input asp-for="ProfileId" hidden />
            <h4>Add Education.</h4>
            <hr />

            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="row">
                <div class="col-md-12">
                    <h4 class="mt-xl mb-lg pb-none text-uppercase">Education Details</h4>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <label for="Title" class="control-label">Title: </label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <label for="Institution" class="control-label">Institution: </label>
                    <input asp-for="Institution" class="form-control" />
                    <span asp-validation-for="Institution" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <label for="Address" class="control-label">Address: </label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6">
                    <label asp-for="StartYear" class="control-label">Start Year</label>
                    <input asp-for="StartYear" class="form-control" />
                    <span asp-validation-for="StartYear" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="EndYear" class="control-label">End Year</label>
                    <input asp-for="EndYear" class="form-control" data-geo="locality" />
                    <span asp-validation-for="EndYear" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-6 col-md-6">
                    <label class="control-label">&nbsp;</label>
                    <br />
                    <button type="submit" class="btn btn-default pull-right">Save Education</button>
                </div>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    
}

WaiterService/Views/Education/Edit.cshtml
@model Education
@{
    ViewData["Title"] = "Edit Education";
}

@section Styles
{

}


<div class="container">
    <div class="col-md-6">
        <form asp-controller="Education" asp-action="Edit" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
            <input asp-for="ProfileId" hidden />
            <input asp-for="ID" hidden />
            <h4>Edit Education.</h4>
            <hr />

            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="row">
                <div class="col-md-12">
                    <h4 class="mt-xl mb-lg pb-none text-uppercase">Education Details</h4>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <h4 class="mt-xl mb-lg pb-none text-uppercase">Education Details</h4>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <label for="Title" class="control-label">Title: </label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <label for="Institution" class="control-label">Institution: </label>
                    <input asp-for="Institution" class="form-control" />
                    <span asp-validation-for="Institution" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <label for="Address" class="control-label">Address: </label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6">
                    <label asp-for="StartYear" class="control-label">Start Year</label>
                    <input asp-for="StartYear" class="form-control" />
                    <span asp-validation-for="StartYear" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="EndYear" class="control-label">End Year</label>
                    <input asp-for="EndYear" class="form-control" data-geo="locality" />
                    <span asp-validation-for="EndYear" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-6 col-md-6">
                    <label class="control-label">&nbsp;</label>
                    <br />
                    <button type="submit" class="btn btn-default pull-right">Update Education</button>
                </div>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

}

WaiterService/Views/Education/Index.cshtml
@model Education[]
@{
    ViewData["Title"] = "Skills";
    var count = 0;
}

@section Styles
{
    <link href="~/lib/selectize/dist/css/selectize.css" rel="stylesheet" />
}


<div class="container">
    <div class="col-md-offset-2 col-md-8">
        <h4>Your Educations</h4>
        <hr />

        <a asp-controller="Education" asp-action="Create" class="btn btn-default mr-xs mb-sm">Add New Education</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Institution
                    </th>
                    <th>
                        Start Year
                    </th>
                    <th>
                        End Year
                    </th>
                    <th>
                        
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var Education in Model)
                    {
                        <tr>
                            <td>
                                @(++count)
                            </td>
                            <td>
                                @Education.Title
                            </td>
                            <td>
                                @Education.Institution
                            </td>
                            <td>
                                @Education.StartYear
                            </td>
                            <td>
                                @Education.EndYear
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="Education" asp-route-id="@Education.ID" class="btn btn-default btn-xs mr-xs mb-sm">Edit</a>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <script>
        $(document).ready(function () {
            
        });
    </script>
}