WaiterService/Models/ViewModels/SearchViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WaiterService.Models.ViewModels
{
    public class SearchViewModel : Job
    {
        public List<SelectListItem> CategoriesList { get; set; }
        public List<SelectListItem> SkillsList { get; set; }
        public Job[] Jobs { get; set; }
    }
}

WaiterService/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using WaiterService.Models;
using WaiterService.Models.AccountViewModels;
using WaiterService.Services;
using WaiterService.Middleware;
using WaiterService.Data;
using WaiterService.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using Itenso.TimePeriod;

namespace WaiterService.Controllers
{
    public class SearchController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly ApplicationDbContext _context;

        public SearchController(
            UserManager<ApplicationUser> userManager,
            ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        //GET: /Search/Index
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // If authenticated user, match experience
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.Identity.GetUserId();
                // Get profile slots
                var pSlots = await _context.UserSlots
                                .Where(s => s.ProfileId == userId)
                                .ToListAsync();
                // Get job slots
                var jSlots = await _context.JobSlots
                                // Only current and future jobs
                                .Where(s => s.EndTime > DateTime.Now)
                                .ToListAsync();
                // Find slot matches
                var sMatchIds = jSlots.
                               Where(j => pSlots.Any(
                                   p => new TimeRange(p.StartTime, p.EndTime).HasInside(new TimeRange(j.StartTime, j.EndTime))
                               ))
                               .Select(s => s.ID).ToList();
                //return Json(sMatchIds);

                // Get profile experiences
                var pExperiences = await _context.UserExperiences
                                .Where(e => e.ProfileId == userId)
                                .ToListAsync();
                // Get job experiences
                var jExperiences = await _context.JobExperiences
                                .ToListAsync();
                // Find experience matches
                var eMatchIds = jExperiences.Intersect(pExperiences, new ExperienceComparer()).Select(e => e.ID).ToList();
                //return Json(eMatchIds);

                var temp = from jobs in _context.Set<Job>()
                           .Include(j => j.Experience.Category)
                           .Include(j => j.Experience.Skill)
                           .Include(j => j.Slot)
                           .Include(j => j.Location)
                           .Include(j => j.CompanyProfile)
                           where eMatchIds.Contains(jobs.Experience.ID) && sMatchIds.Contains(jobs.Slot.ID)
                           orderby jobs.ID descending
                           select jobs;

                return View(await temp.Take(6).ToArrayAsync());
            }

            var query = from jobs in _context.Set<Job>()
                        .Include(j => j.Experience.Category)
                        .Include(j => j.Experience.Skill)
                        .Include(j => j.Slot)
                        .Include(j => j.Location)
                        .Include(j => j.CompanyProfile)
                        orderby jobs.ID descending
                        select jobs;

            var model = await query.Take(6).ToArrayAsync();

            return View(model);
        }

        
        //GET: /Search/Query
        [HttpGet]
        public IActionResult Query()
        {
            var model = new JobViewModel();
            model.Location = new Location();
            
            var categories = _context.Categories.ToList();
            var skills = _context.Skills.ToList();
            model.CategoriesList = categories.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = Convert.ToString(c.ID)
            }).ToList();
            model.SkillsList = skills.Select(s => new SelectListItem()
            {
                Text = s.Name,
                Value = Convert.ToString(s.ID)
            }).ToList();

            return View(model);
        }
    }
}

WaiterService/Views/Search/Index.cshtml
@model Job[]
@{
    ViewData["Title"] = "Jobs Search";
}

@section Styles
{
    <link href="~/lib/selectize/dist/css/selectize.css" rel="stylesheet" />
    <link href="~/vendor/pickadate/lib/themes/default.css" rel="stylesheet"/>
    <link href="~/vendor/pickadate/lib/themes/default.date.css" rel="stylesheet" />
    <link href="~/vendor/pickadate/lib/themes/default.time.css" rel="stylesheet" />
}

<section class="section section-no-background section-no-border m-none">
    @*<div class="container">
        <h4>Filters</h4>
        <hr />

        <form asp-controller="Search" asp-action="Edit" asp-route-returnurl="@ViewData["ReturnUrl"]" method="get" class="form-horizontal">
            <div class="form-group">
                <div class="col-md-3">
                    <label class="control-label">Category: </label>
                    <select class="form-control"></select>
                    <span class="text-danger"></span>
                </div>
                <div class="col-md-3">
                    <label class="control-label">Skill: </label>
                    <select class="form-control"></select>
                    <span class="text-danger"></span>
                </div>
                <div class="col-md-3">
                    <label class="control-label">Skill: </label>
                    <select class="form-control"></select>
                    <span class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-6 col-md-6">
                    <label class="control-label">&nbsp;</label>
                    <br />
                    <button type="submit" class="btn btn-default pull-right">Search Jobs</button>
                </div>
            </div>

        </form>
    </div>*@

    <div class="container">
        <h4>Matched Jobs.</h4>
        <hr />

        @if (Model != null)
        {
            if (Model.Count() < 1)
            {
                <h5> No records.</h5>
            }

            @foreach (var Job in Model)
            {
                <div class="col-md-4">
                    <div class="micro-map box-shadow-custom clearfix">
                        <div class="micro-map-info">
                            <div class="micro-map-info-detail">
                                <h6>@Job.Experience.Skill.Name (@Job.Experience.Category.Name)</h6>
                                <h6>@Job.CompanyProfile.CompanyName</h6>
                                <a asp-action="Details" asp-controller="Job" asp-route-id="@Job.ID" class="btn btn-primary btn-md font-size-sm text-uppercase mb-md"><i class="icon-calendar icons ml-sm"></i> @Job.Slot.StartTime.ToString("dd/MM/yy") [@Job.Slot.StartTime.ToString("HH:mm") - @Job.Slot.EndTime.ToString("HH:mm")]</a>
                                <strong><i class="icon-location-pin icons text-color-primary"></i> @Job.Location.Name</strong>
                            </div>
                        </div>
                    </div>
                    <br />
                </div>
            }
        }

        <br />
    </div>
</section>


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDTrJ9dyaYyB-3UNhEa4P4MQ6jn7Fg4dxA&amp;libraries=places"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

    <script>
        var info;
        $(function () {
           
        });
    </script>

    <script>
        $(document).ready(function () {
            
        });
    </script>
}